spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.gdyzhnhijyfgohtlbfqd
spring.datasource.password=ParaTOd0s2724
